#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server:

#Requirements:

#Accepts 4 parameters
#The path to the file to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses
#Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
#scp must transfer the file to the user home directory ~/
#Strict host key checking must be disabled when using scp
usage() {
echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}
if [ "$#" -lt 4 ]; then
    usage
fi
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
