#!/usr/bin/env bash
#Script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Yiiiiii U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid
trap echo '"I hate the kill command"' 15
trap echo '"Yiiiiii U no love me?!"; exit' 2
trap echo 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM
while true
do
	echo "To infinity and beyond"
done
