#!/usr/bin/env bash
#Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
#Requirements:
#You cannot use pgrep
#The third line of your script must be # shellcheck disable=SC2009 (for more info about ignoring shellcheck error here)
./1-list_your_processes | grep "bash"
