#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd
file=/etc/passwd
while IFS=: read -r username passwd uid gid fullname homedir shell;
do
	echo "username: $username, User Id: $uid, homedir: $homedir"
done < $file
