#!/usr/bin/env bash
#Script that displays Best School 10 times
#but for the 9th iteration display Best School then hi
i=10
while [ $i -le 10]
do
	if [ $i =! 9 ]
		echo "Best School"
	else
		echo "Hi"
		((i++))
	fi
done
