#!/usr/bin/env bash
# Script that displays Best School 10 times
# but for the 9th iteration displays Best School then hi
i=0
while [ $i -lt 10 ]
do
        if [ $i -ne 8 ]; then
                echo "Best School"
        else
                echo "Hi"
        fi
        ((i++))
done
