#!/usr/bin/env bash
# Script that displays the content of the current directory
# In a list format, showing only the part of the name after the first dash

for item in *
do
    if [[ "$item" == *-* ]]; then
        new_name="${item#*-}"
        echo "$new_name"
    else
        echo "$item"
    fi
done
